In [13]:
import pandas as pd
iData_WebMD = pd.read_csv (r"C:\Users\Varsha.bilwar\Desktop\archive\webmd.csv")
iData_WebMD.drop( 'Condition',axis=1)
print(iData_WebMD)
iData_WebMD.head()
iData_WebMD.shape
iData_WebMD.describe

               Age      Condition        Date                          Drug  \
0       75 or over    Stuffy Nose   9/21/2014                  25dph-7.5peh   
1            25-34  Cold Symptoms   1/13/2011                  25dph-7.5peh   
2            65-74          Other   7/16/2012  warfarin (bulk) 100 % powder   
3       75 or over          Other   9/23/2010  warfarin (bulk) 100 % powder   
4            35-44          Other    1/6/2009  warfarin (bulk) 100 % powder   
...            ...            ...         ...                           ...   
362801       55-64   Stop Smoking  11/14/2008                       chantix   
362802                      Other  11/14/2008                       chantix   
362803       25-34   Stop Smoking  11/13/2008                       chantix   
362804       55-64   Stop Smoking  11/13/2008                       chantix   
362805       45-54   Stop Smoking  11/12/2008                       chantix   

        DrugId  EaseofUse  Effectiveness  \
0      

<bound method NDFrame.describe of                Age      Condition        Date                          Drug  \
0       75 or over    Stuffy Nose   9/21/2014                  25dph-7.5peh   
1            25-34  Cold Symptoms   1/13/2011                  25dph-7.5peh   
2            65-74          Other   7/16/2012  warfarin (bulk) 100 % powder   
3       75 or over          Other   9/23/2010  warfarin (bulk) 100 % powder   
4            35-44          Other    1/6/2009  warfarin (bulk) 100 % powder   
...            ...            ...         ...                           ...   
362801       55-64   Stop Smoking  11/14/2008                       chantix   
362802                      Other  11/14/2008                       chantix   
362803       25-34   Stop Smoking  11/13/2008                       chantix   
362804       55-64   Stop Smoking  11/13/2008                       chantix   
362805       45-54   Stop Smoking  11/12/2008                       chantix   

        DrugId  E

In [16]:
from sklearn.model_selection import train_test_split
y = iData_WebMD.Satisfaction
X = iData_WebMD.DrugId
X_train, X_test, y_train, y_test = train_test_split( X, y , test_size=0.2)
print("\nX_train\n")
print(X_train.head())
print("\n")
print(X_train.shape)

print("\nX_test:\n")
print(X_test.head())
print("\n")
print(X_test.shape)

print("\nY_test:\n")
print(y_train.head())
print("\n")
print(y_train.shape)

print("\nY_test:\n")
print(y_test.head())
print("\n")
print(y_test.shape)


X_train

86000     11285
308592     3721
98222      8674
356152     4067
131152     5869
Name: DrugId, dtype: int64


(290244,)

X_test:

59865      1025
5690       6616
202865     4497
100601    13706
5336      16188
Name: DrugId, dtype: int64


(72562,)

Y_test:

86000     4
308592    1
98222     1
356152    4
131152    1
Name: Satisfaction, dtype: int64


(290244,)

Y_test:

59865     4
5690      1
202865    5
100601    3
5336      1
Name: Satisfaction, dtype: int64


(72562,)


In [19]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(np.array(X_train).reshape(-1,1),y_train)

LogisticRegression()

In [25]:
y_pred = classifier.predict(np.array(X_test).reshape(-1,1))
print( y_pred )

[1 1 1 ... 1 1 1]


In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print( cm )

[[20076     0     0     0    16]
 [ 7247     0     0     0    11]
 [10240     0     0     0    12]
 [12487     0     0     0    20]
 [22425     0     0     0    28]]
